version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      NODE_ENV: production
      UPLOAD_DIRECTORY: /app/uploads
      DATABASE_URL: postgres://postgres:password@database:5432/mydatabase
    restart: always

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://backend:5000
    restart: always
    depends_on:
      - backend
      - database

volumes:
  db_data: